word_1 = input("zadaj 1. slovo: ")
word_2 = input("zadaj 2. slovo: ")
word_3 = input("zadaj 3. slovo: ")

print(f"{word_1} {word_2} {word_3}")
print(f"{word_1} {word_3} {word_2}")
print(f"{word_2} {word_1} {word_3}")
print(f"{word_2} {word_3} {word_1}")
print(f"{word_3} {word_1} {word_2}")
print(f"{word_3} {word_2} {word_1}")